### PR TITLE
APIRequester.Call *http.Header -> http.Header

### PR DESCRIPTION
**Pull request by karlseguin**
Since http.Header is just a map, and maps are already reference types
there's no point in an additional indirection (and a very tiny
performance cost to having it)

(My Go is a little rusty, so maybe I'm wrong about this?? But don't think so)

### CODE REVIEW

**Comment by hecharles** [comment]
hi @karlseguin Thank you for your interest in contributing to xendit-go. unfortunately we just add new feature recently and it make this PR cannot pas integration test

**Comment by hecharles** [comment]
hi @karlseguin Thank you for your interest in contributing to xendit-go. unfortunately we just add new feature recently and it make this PR cannot pas integration test

**Comment by karlseguin** [comment]
Hi @hecharles

I updated the code to handle the new/changed calls. Are there directions anywhere that explain how / what I need to setup on my test account to get the integration tests fully working?

**Comment by hecharles** [comment]
@karlseguin no need to setup account if you only want to test the sdk. use this key instead [https://github.com/xendit/xendit-go/blob/95426ec18f3dad481111b20a0013a7ff8b72d305/.github/workflows/test.yml#L28]

**Pull request merged**
